data:
  dataset: cifar10_benchmark
  dataset_path: null
  num_workers: 0
  target_size: 32
evaluation: true
experiment:
  deterministic: false
  name: dfa_adam
  output_dir: trained_models/cifar10/le_net_cifar/
  seed: 2021
infrastructure:
  gpus: -1
model:
  architecture: le_net_cifar
  loss_function:
    name: cross_entropy
  mode:
    options:
      constrain_weights: false
      gradient_clip: false
      init: xavier
    type: dfa
  pretrained: false
training:
  hyperparameters:
    batch_size: 128
    epochs: 250
  lr_scheduler:
    gamma: 0.1
    milestones:
    - 100
    - 150
    - 200
    type: multistep_lr
  metrics:
    display_iterations: 500
    layer_alignment: true
    top_k: 5
    weight_ratio: true
  optimizer:
    betas:
    - 0.9
    - 0.999
    lr: 0.0001
    momentum: 0.9
    type: Adam
    weight_decay: 0.0001
